<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34257" started-at="2019-10-03T20:27:17Z" finished-at="2019-10-03T20:27:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34257" started-at="2019-10-03T20:27:17Z" finished-at="2019-10-03T20:27:51Z">
      <class name="igt.tableMountain.qa.testcases.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="setUp" is-config="true" duration-ms="11834" started-at="2019-10-03T13:27:17Z" finished-at="2019-10-03T13:27:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginPageTitiletest()[pri:1, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="loginPageTitiletest" duration-ms="17" started-at="2019-10-03T13:27:29Z" finished-at="2019-10-03T13:27:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitiletest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="tearDown" is-config="true" duration-ms="168" started-at="2019-10-03T13:27:29Z" finished-at="2019-10-03T13:27:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="setUp" is-config="true" duration-ms="10519" started-at="2019-10-03T13:27:29Z" finished-at="2019-10-03T13:27:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="igtLogoTest()[pri:2, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="igtLogoTest" duration-ms="196" started-at="2019-10-03T13:27:39Z" finished-at="2019-10-03T13:27:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at igt.tableMountain.qa.testcases.LoginPageTest.igtLogoTest(LoginPageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- igtLogoTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="tearDown" is-config="true" duration-ms="165" started-at="2019-10-03T13:27:39Z" finished-at="2019-10-03T13:27:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="setUp" is-config="true" duration-ms="10620" started-at="2019-10-03T13:27:40Z" finished-at="2019-10-03T13:27:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest()[pri:3, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="loginTest" duration-ms="546" started-at="2019-10-03T13:27:50Z" finished-at="2019-10-03T13:27:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:igt.tableMountain.qa.testcases.LoginPageTest@5ce81285]" name="tearDown" is-config="true" duration-ms="161" started-at="2019-10-03T13:27:51Z" finished-at="2019-10-03T13:27:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- igt.tableMountain.qa.testcases.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
